CREATE TABLE racedirector_races (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  created_by INTEGER
    REFERENCES raceDirector_users(id) ON DELETE SET NULL NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);