CREATE TABLE raceDirector_races (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  race_name TEXT NOT NULL,
  race_date TEXT NOT NULL,
  race_time TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  created_by INTEGER
    REFERENCES raceDirector_users(id) ON DELETE CASCADE NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);