CREATE TABLE raceDirector_finishers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  race_id INTEGER
    REFERENCES raceDirector_races(id) ON DELETE CASCADE NOT NULL,
  finisher_name TEXT NOT NULL,
  finisher_time TEXT,
  finisher_place TEXT NOT NULL,
  gender TEXT,
  age INTEGER,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);